//
//  AppDelegate.swift
//  Baqala
//
//  Created by Macbook on 03/12/2018.
//  Copyright © 2018 My Technology. All rights reserved.
//

import UIKit
import CoreData
import IQKeyboardManagerSwift
import GoogleMaps
import GooglePlaces
import FBSDKCoreKit
import FBSDKLoginKit
import GoogleSignIn
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

       static let appDelegate = UIApplication.shared.delegate as! AppDelegate
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        //Mark:- Set BGcolor Of statusBar
        let statusBar: UIView = UIApplication.shared.value(forKey: "statusBar") as! UIView
        if statusBar.responds(to:#selector(setter: UIView.backgroundColor)) {
            statusBar.backgroundColor = UIColor(red:1/255, green:136/255, blue:39/255, alpha: 1)
        }
        UIApplication.shared.statusBarStyle = .lightContent
       
        
        
        
         PayPalMobile .initializeWithClientIds(forEnvironments: [PayPalEnvironmentSandbox: "AR9DVJvSCQyaYqojNmNyjPaz14YM17PkPJ3KlyCbDfEOg4WYZAYctEF5s6Dxkxx-jVWva2xCXOXHWGvl"])
        //MARK:-
        IQKeyboardManager.shared.enable = true
        //fix me
        GMSPlacesClient.provideAPIKey("AIzaSyCaF2LSRHDzC-NdWZg_c1cQIbmWjiEX2Kw")
        
        //owner of integrated account -> sir manzor
        //editor role: nvd, key generated by nvd   IOS restricted key
        GMSServices.provideAPIKey("AIzaSyCvaIuO82At02qo4KT6M3k1ljs6y4zxj_Y")
        FBSDKApplicationDelegate.sharedInstance()?.application(application, didFinishLaunchingWithOptions: launchOptions)
        GIDSignIn.sharedInstance()?.clientID = "1011830164805-00ntaorvb7r75krvd81q2qd09mguu6dg.apps.googleusercontent.com"
        
    
        
        //Handle login navigation on this method
        self.refreshDataOnStartup()
      
        
     
        return true
    }

    

    
    func moveToHome(){
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let tabbarVC = storyboard.instantiateViewController(withIdentifier: "VCTabBarHome") as! VCTabBarHome
        let navigationVC: UINavigationController = UINavigationController(rootViewController: tabbarVC)
        self.window?.rootViewController = navigationVC
        self.window?.makeKeyAndVisible()
    }
    
    func moveToLogin(){
       
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let logINN = storyboard.instantiateViewController(withIdentifier: "LoginVC") as! LoginVC
        let nvc: UINavigationController = UINavigationController(rootViewController: logINN)
//        self.window?.rootViewController = nvc
        self.window?.switchRootViewController(nvc)
        self.window?.makeKeyAndVisible()
    }
    
    func moveToSelectlanguage(){
        

        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let logINN = storyboard.instantiateViewController(withIdentifier: "VCSelectLanguage") as! VCSelectLanguage
        let nvc: UINavigationController = UINavigationController(rootViewController: logINN)
         nvc.navigationItem.hidesBackButton = true
        //self.window?.rootViewController = nvc
        self.window?.switchRootViewController(nvc)
        self.window?.makeKeyAndVisible()
    }
    
    func moveToEmailVerification(){
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let logINN = storyboard.instantiateViewController(withIdentifier: "VCEmailVerification") as! VCEmailVerification
        let nvc: UINavigationController = UINavigationController(rootViewController: logINN)
        nvc.navigationItem.hidesBackButton = true
        self.window?.rootViewController = nvc
        self.window?.makeKeyAndVisible()
    }
    
    
    func moveToSocialLogin(){
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let logINN = storyboard.instantiateViewController(withIdentifier: "ContinueAsGuestandSocialLogin") as! ContinueAsGuestandSocialLogin
        let nvc: UINavigationController = UINavigationController(rootViewController: logINN)
        nvc.navigationItem.hidesBackButton = true
        self.window?.rootViewController = nvc
        self.window?.makeKeyAndVisible()
    }
    
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        
        let handler:Bool = FBSDKApplicationDelegate.sharedInstance().application(app, open: url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplication.OpenURLOptionsKey.annotation])
        
        //MARK:- GoogLeSignin
        GIDSignIn.sharedInstance()?.handle(url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplication.OpenURLOptionsKey.annotation])
        
        return handler
    }
    
    
    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
        // Saves changes in the application's managed object context before the application terminates.
        self.saveContext()
    }

   
    
    
    
    
    // MARK: - Core Data stack

    lazy var persistentContainer: NSPersistentContainer = {
        /*
         The persistent container for the application. This implementation
         creates and returns a container, having loaded the store for the
         application to it. This property is optional since there are legitimate
         error conditions that could cause the creation of the store to fail.
        */
        let container = NSPersistentContainer(name: "Baqala")
        container.loadPersistentStores(completionHandler: { (storeDescription, error) in
            if let error = error as NSError? {
                // Replace this implementation with code to handle the error appropriately.
                // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
                 
                /*
                 Typical reasons for an error here include:
                 * The parent directory does not exist, cannot be created, or disallows writing.
                 * The persistent store is not accessible, due to permissions or data protection when the device is locked.
                 * The device is out of space.
                 * The store could not be migrated to the current model version.
                 Check the error message to determine what the actual problem was.
                 */
                fatalError("Unresolved error \(error), \(error.userInfo)")
            }
        })
        return container
    }()

    // MARK: - Core Data Saving support

    func saveContext () {
        let context = persistentContainer.viewContext
        if context.hasChanges {
            do {
                try context.save()
            } catch {
                // Replace this implementation with code to handle the error appropriately.
                // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
                let nserror = error as NSError
                fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
            }
        }
    }

}


extension AppDelegate {
   
    func refreshDataOnStartup()  {
        
        setScreenBySession()
        
        //Selected User Type
        self.setMyDefaultAccountType()
    }
    
    
    fileprivate func setScreenBySession() {
        //Reset User Defaults
        Sharedata.shareInfo.isFromSettingVC = false
        
        //Navigate to Specific screen
        if Sharedata.shareInfo.email == nil {
            self.moveToSelectlanguage()
        }
            
        else if Sharedata.shareInfo.emailIsVerfied ?? false  == false {
            self.moveToLogin()
        }
        else {
            self.moveToHome()
        }
    }
    
    func setMyDefaultAccountType() {
        
        if(Sharedata.shareInfo.accountType == "guest") {
            myDefaultAccountType = .guest
        }
        else if( Sharedata.shareInfo.accountType == "buyer"){
            myDefaultAccountType = .buyer
        }
        else if( Sharedata.shareInfo.accountType == "seller"){
            myDefaultAccountType = .seller
        }
        else {
            myDefaultAccountType = .notExist
        }
        
        //Call
        setMyDefaultLanguage()
    }
    
    
    func setMyDefaultLanguage()  {
        
        guard let lang = UserDefaults.standard.string(forKey: "myDefaultLanguage") else {
            return myDefaultLanguage = .en
        }
      
        switch lang {
        case "ar":
           myDefaultLanguage = .ar
        default: // .en
           myDefaultLanguage = .en
        }

    }
    

}
